require: rubocop-rails

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Metrics/BlockLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true
  Details:
    "Add `# frozen_string_literal: true` to the top of the file. Frozen string
    literals will become the default in a future Ruby version, and we want to make
    sure we're ready."
