version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pekabgt_dev
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    network_mode: service:db
    volumes:
      - redis-data:/data

  app:
    tty: true
    stdin_open: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/home/qiscus/app:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis-data:
